### FreeCAD Foil Library : FCFoil
# 
# Author: Konstantinos POLITIS
# 
#   FreeCAD Library for Managing Foils (interface and manipulation of FOIL Library) 
#   
#  To do list : 
#    - Rework help messages and add input/output text
#    - Add help/readme function to guide used 
# 
###
from FreeCAD import Base
import FreeCAD
import Part

O =Base.Vector(0,0,0)
ux=Base.Vector(1,0,0)
uy=Base.Vector(0,1,0)
uz=Base.Vector(0,0,1)

class Doc:
    """ This is a FreeCAD Document that contains Foil Sections."""
    
    def __init__(self,document_name="MyFoil"):
        """ Create a Named Document (by default the name is MyFoil)  """
        self.Docu=FreeCAD.newDocument(document_name)
        
    
    def add(self,FS,name='Foil Section'):
        """ Create a Named Foil Section as a Part:Feature 
        Input : 
            1. A foil section instance generated by a foil section generating function
            2. The Name of the Section : By default this is Foil Section        """
        self.Docu.addObject("Part::Feature",name).Shape=FS


###
# Foil Section Generating Functions
#

def WAGEN(Z,EAR,rR,tLE=0.,tTE=0,s=0,nps=40,npp=40,Tvp=1,Tvs=1):
    """ Foil Section Generating Function
        Inputs :  
            -Specific for WAGENINGEN 
                Z        : number of blades 
                EAR      : expanded area ratio 
                rR       : non-dimensional section radius 
                tLE      : thickness ratio (over tmax) at Leading Edge (def=0.2)  
                tTE      : thickness ratio (over tmax) at Trailing Edge (def=0)
                s        : smoothing factor, if s=0 no smoothing, if s=1e-4 small smoothing (def=1e-4) 
            -For any foil                                                      
                nps,npp  : number of points to construct splines (suction and pressure side) (def=40) 
                Tvp,Tvs  : 0 or 1, do not use or use tangent vectors at pressure side, suction side (def=1) 
        Output : 
            Foil_Section : A Part Shape object for the section """
    from WAGENINGEN_LIB import WAGENINGEN 
    
    foil=WAGENINGEN(Z,EAR,rR,tLE_tmax=tLE,tTE_tmax=tTE,Use_Original=1,s=s)
    
    print("Generated Foil Section : "+foil.name())
    
    spP,spS = make_splines(foil,nps=nps,npp=npp,Tvp=Tvp,Tvs=Tvs)
    
    Foil_Section=Part.Wire([spP.toShape(),spS.toShape()])
    
    return Foil_Section
        

def NACA(code,nps=40,npp=40,Tv=1):
    """ Foil Section Generating Function
        Inputs :
            -Specific for NACA 
                code     : a four digit code representing the Series four geometry 
                (Digits = 1st digit : max camber, 2nd : location of max camber, 3rd-4rth : thickness)
            -For any foil                                                    
                nps,npp  : number of points to construct splines (suction and pressure side) (def=40) 
                Tvp,Tvs  : 0 or 1, do not use or use tangent vectors at pressure side, suction side (def=1) """
    from NACA_LIB import NACA as NACAPicker
    
    foil=NACAPicker(code)
    
    print("Generated Foil Section : "+foil.name())
    
    sp = make_spline(foil,nps=nps,npp=npp,Tv=Tv)
    
    Foil_Section=Part.Wire(sp.toShape())
    
    return Foil_Section


def NACA2(code,nps=40,npp=40,Tvp=1,Tvs=1):
    """ Foil Section Generating Function
        Inputs :
            -Specific for NACA 
                code     : a four digit code representing the Series four geometry 
                (Digits = 1st digit : max camber, 2nd : location of max camber, 3rd-4rth : thickness)
            -For any foil                                                    
                nps,npp  : number of points to construct splines (suction and pressure side) (def=40) 
                Tvp,Tvs  : 0 or 1, do not use or use tangent vectors at pressure side, suction side (def=1) """
    from NACA_LIB import NACA as NACAPicker
    
    foil=NACAPicker(code)
    
    print("Generated Foil Section : "+foil.name())
    
    spP,spS = make_splines(foil,nps=nps,npp=npp,Tvp=Tvp,Tvs=Tvs)
    
    Foil_Section=Part.Wire([spP.toShape(),spS.toShape()])
    
    return Foil_Section


#
# END : Foil Section Generating Functions
###



###
# Functions for working with FreeCAD
#

def make_spline(afoil,nps=40,npp=40,Tv=1):
    """ Return the spline of the Pressure-Suction side of a foil """
    
    xpres,ypres=afoil.PressureSide_FCAD(npoints=npp)
    xsuc,ysuc=afoil.SuctionSide_FCAD(npoints=nps)

    # NOTE : Total number of point nps+npp-1
    V=[Base.Vector(xpres[i],ypres[i],0) for i in range(len(xpres)-1)] 
    V.extend([Base.Vector(xsuc[i],ysuc[i],0) for i in range(len(xsuc))]) 
          
    # Setup FreeCAD Spline (one spline)
    sp=Part.BSplineCurve()
    
    if (Tv):
        
        # Get tangent vector at trailing edge
        vecTE=afoil.vecS_TE()
        vTEp = Base.Vector(vecTE[0],vecTE[1],0)
        vTEs = Base.Vector(vecTE[2],vecTE[3],0)
        
        # Set spline
        sp.interpolate(V,InitialTangent=vTEp,FinalTangent=vTEs)
        
    else:
        sp.interpolate(V)
    
    return sp


def make_splines(afoil,nps=40,npp=40,Tvp=1,Tvs=1):
    """ Returns the splines of the Pressure and Suction side of a foil """
    
    xpres,ypres=afoil.PressureSide_FCAD(npoints=npp)
    xsuc,ysuc=afoil.SuctionSide_FCAD(npoints=nps)
    #xsuc,ysuc=afoil.SuctionSide_FCAD(npoints=nps,LE2TE=False)

    #Vp=[Base.Vector(xpres[i],ypres[i],0) for i in range(len(xpres))] 
    #Vs=[Base.Vector(xsuc[i],ysuc[i],0) for i in range(len(xsuc))] 
    Vp=[xpres[i]*ux+ypres[i]*uy for i in range(len(xpres))] 
    Vs=[xsuc[i]*ux+ysuc[i]*uy for i in range(len(xsuc))] 
    
    if (Tvp or Tvs):
        
        # Get tangent vector at leading/trailing edge
        vecLE=afoil.vecS_LE()
        vecTE=afoil.vecS_TE()
        
        # Arrange Data
        vLEp = Base.Vector(vecLE[0],vecLE[1],0)
        vLEs = Base.Vector(vecLE[2],vecLE[3],0)
        vTEp = Base.Vector(vecTE[0],vecTE[1],0)
        vTEs = Base.Vector(vecTE[2],vecTE[3],0)
    
    # Setup FreeCAD Splines (two splines)
    spS=Part.BSplineCurve()
    spP=Part.BSplineCurve()
    
    if (Tvp):
        spP.interpolate(Vp,InitialTangent=vTEp,FinalTangent=vLEp)
    else:
        spP.interpolate(Vp)
    
    if (Tvs):    
        spS.interpolate(Vs,InitialTangent=vLEs ,FinalTangent=vTEs)
        #spS.interpolate(Vs,InitialTangent=vTEs ,FinalTangent=vLEs)
    else:
        spS.interpolate(Vs)
    
    return spP,spS


#
# END : Functions for working with FreeCAD
###

def README():
    """ Help """
    instru='''
    This library helps you create foil sections and established the required operations 
    to facilitate the geometrical constructions. If you need more details about the 
    construction methods used you should check the theory manual. This message provides
    you with the basics to begin your work.
    
    1. Create a document that will contain the sections of a foil :
        The document is created by calling FCFoils.Doc as for exemple :
        
                 MyFoils=FCFoil.Doc() or MyFoils=FCFoil.Doc("optional_name").
        
        The default optional name is MyFoil.
        We will add the foil section to this document.
        Multiple documents can be managed in the same manner.
        In terms of FreeCAD this is a FreeCAD Document instance.
    
    2. Create the foil sections :
        The functions : 
            Wagen, NACA, ...
        create foil section instances, for exemple: 
        
                 FS1=FCFoil.WAGEN(Z=4,EAR=1,rR=0.4)
        
        the FS1 is a foil section instance. In terms of FreeCAD this a Part.Shape 
        instance and thus shares all the methods of Part.Shape objects.
        Multiple foil sections can be created (note that you have to store them to 
        different variables (if this is required). 
        
        Different options are required for different function that generate foil section:
                NACA  : A code that is related to a NACA Series 
                WAGEN : Number of blades, EAR, etc
                
        To check in detail the required input per foil generating function, type : 
        
                FCFoil. or FCFoil.(with a dot). 
                
        A list appears with the name of the module functions. Move the cursor to the 
        name of the foil generating function to see in detail the required and optional input.
        Optional inputs are identified with a default value.  
        
    3. Add the foil section to the document
        If FS1 is a foil section created by either function Wagen or NACA, that is for :
        then :
                 MyFoils.add(FS1) will extend your document with the foil section FS1
        
        At this point the foil section appears on screen.
        You may optionally provide a name MyFoils.add(FC1,'MyFoilName').
    
    NOTE : The following is a listing of commands to test the library :
    
import FCFoil
MyFoil=FCFoil.Doc("My Foil")
FS1=FCFoil.WAGEN(Z=4,EAR=1,rR=0.4)
MyFoil.add(FS1)
FS2=FCFoil.NACA(4430)
MyFoil.add(FS2)
    
    
    You may copy-paste the commands to the Python console to test the functionallity of
    the library (explained above). Note that Python is case-sensitive ! 
    
    End of README
        '''
    print(instru)

